#! /bin/sh
sxhkd &
compton &
tint2 &
dunst &
parcellite &
numlockx &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc merge_overlapping_monitors true

bspc config normal_border_color
bspc config active_border_color  \#145f9d
bspc config focused_border_color \#145f9d

bspc config pointer_modifier mod1

bspc config pointer_action1 move

bspc config pointer_action2 resize_corner

bspc config top_padding 0

bspc rule -a plasmashell state=floating

# bspc config automatic_scheme longest_side

# bspc config initial_polarity second_child
# bspc config automatic_scheme spiral
# bspc config initial_polarity first_child

